package api

// Code generated by Python AST scanner from official OpenWebUI repository.
// DO NOT EDIT MANUALLY - Exact Pydantic model mappings to Golang structs.

// --- Chat Models ---

type OpenWebUIChatTitleIdResponse struct {
	ID         string  `json:"id"`
	Title      string  `json:"title"`
	UpdatedAt  int64   `json:"updated_at"`
	CreatedAt  int64   `json:"created_at"`
	LastReadAt *int64  `json:"last_read_at,omitempty"`
	Snippet    *string `json:"snippet,omitempty"`
	Active     bool    `json:"active"`
	Archived   bool    `json:"archived"`
	Pinned     bool    `json:"pinned"`
}

type OpenWebUIChatResponse struct {
	ID               string         `json:"id"`
	UserID           string         `json:"user_id"`
	Title            string         `json:"title"`
	Chat             any            `json:"chat"`
	UpdatedAt        int64          `json:"updated_at"`
	CreatedAt        int64          `json:"created_at"`
	ShareID          *string        `json:"share_id,omitempty"`
	Archived         bool           `json:"archived"`
	Pinned           bool           `json:"pinned"`
	Meta             map[string]any `json:"meta,omitempty"`
	Variables        map[string]any `json:"variables,omitempty"`
	FolderID         *string        `json:"folder_id,omitempty"`
	Summary          *string        `json:"summary,omitempty"`
	CurrentMessageID *string        `json:"current_message_id,omitempty"`
}

type OpenWebUIChatConfigForm struct {
	ContextCompactionModel              string `json:"CONTEXT_COMPACTION_MODEL"`
	EnableContextCompaction             bool   `json:"ENABLE_CONTEXT_COMPACTION"`
	ContextCompactionTokenThreshold     int64  `json:"CONTEXT_COMPACTION_TOKEN_THRESHOLD"`
	ContextCompactionTokenCap           int64  `json:"CONTEXT_COMPACTION_TOKEN_CAP"`
	ContextCompactionRetentionPercentage int64  `json:"CONTEXT_COMPACTION_RETENTION_PERCENTAGE"`
	ContextCompactionPromptTemplate     string `json:"CONTEXT_COMPACTION_PROMPT_TEMPLATE"`
	EnableToolPermissions               bool   `json:"ENABLE_TOOL_PERMISSIONS"`
}

// --- Folder Models ---

type OpenWebUIFolderNameIdResponse struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Meta        map[string]any `json:"meta,omitempty"`
	ParentID    *string        `json:"parent_id"`
	IsExpanded  bool           `json:"is_expanded"`
	UnreadCount int            `json:"unread_count"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

// --- List/Pagination Responses ---

type OpenWebUIPaginatedListResponse struct {
	Items []any `json:"items"`
	Total int64 `json:"total"`
}

// --- User Models ---

type OpenWebUIUserSettings struct {
	UI map[string]any `json:"ui"`
}

type OpenWebUIUserPermissions struct {
	Workspace map[string]bool `json:"workspace"`
	Chat      map[string]bool `json:"chat"`
}

// --- Config Models ---

type OpenWebUITaskConfigForm struct {
	TaskModel                    string `json:"TASK_MODEL"`
	TaskModelExternal            string `json:"TASK_MODEL_EXTERNAL"`
	EnableTitleGeneration        bool   `json:"ENABLE_TITLE_GENERATION"`
	EnableTagsGeneration         bool   `json:"ENABLE_TAGS_GENERATION"`
	EnableAutocompleteGeneration bool   `json:"ENABLE_AUTOCOMPLETE_GENERATION"`
}

type OpenWebUIConnectionsConfigForm struct {
	EnableDirectConnections  bool `json:"ENABLE_DIRECT_CONNECTIONS"`
	EnableDirectIntegrations bool `json:"ENABLE_DIRECT_INTEGRATIONS"`
	EnableBaseModelsCache    bool `json:"ENABLE_BASE_MODELS_CACHE"`
}

type OpenWebUIToolServersConfigForm struct {
	ToolServerConnections []any `json:"TOOL_SERVER_CONNECTIONS"`
}

type OpenWebUIAdminConfig struct {
	ShowAdminDetails bool   `json:"SHOW_ADMIN_DETAILS"`
	AdminEmail       string `json:"ADMIN_EMAIL"`
	WebuiURL         string `json:"WEBUI_URL"`
	EnableLoginForm  bool   `json:"ENABLE_LOGIN_FORM"`
	EnableSignup     bool   `json:"ENABLE_SIGNUP"`
	EnableAPIKeys    bool   `json:"ENABLE_API_KEYS"`
	EnableFolders    bool   `json:"ENABLE_FOLDERS"`
	EnableChannels   bool   `json:"ENABLE_CHANNELS"`
}
